services:
  legalpha:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: python main.py --test --test_size 0.1

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/mongodb
    env_file:
      - .env

volumes:
  mongodb: