services:
  legalpha:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: python main.py --tune --model-name bert-embedding-classifier --tune-iters 1 --tune-cv-folds 5
    # command: python main.py --test --model-name bert-embedding-classifier
    # command: python main.py --train

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/mongodb
    env_file:
      - .env

volumes:
  mongodb: